FROM centos:7
RUN yum install wget -y
RUN wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat/jenkins.repo
RUN rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
RUN yum install java-latest-openjdk -y
RUN yum install jenkins -y
RUN yum install git -y
CMD java -jar/usr/lib/jenkins/jenkins.war
